config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users
  resources :events
  root 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :date, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, presence: true
  validates :surname, presence: true
  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true

  def editor?
    self.role == 'editor'
  end

  def admin?
    self.role == 'admin'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end
  def show
    params.inspect
    @event = Event.find(params[:id])
  end
  def new
    @event = Event.new
  end
  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to (events_path())
    else
      render :new
    end
  end
  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if (@event.update_attributes(event_params))
      redirect_to (event_path(@event))
    else
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    event_name = @event.name
    @event.destroy
    flash[:notice] = "Event #{event_name} is deleted"
    redirect_to events_path()
  end

  def event_params
    params.require(:event).permit(:name, :date, :description, :image)
  end
  private :event_params
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    puts 'patka'

    user = User.find_by_email(params[:sessions][:email])
    puts 'user find'
    if user && user.authenticate(params[:sessions][:password])
      puts 'in if'
      session[:user_id] = user.id
      redirect_to root_url
    else
      puts 'in else'
      redirect_to login_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_user, only: [:index, :show]

  def index
    @users = User.all
  end

  def show
    params.inspect
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      puts 'prvi dio'
      session[:user_id] = @user.id
      puts 'drugi dio'
      redirect_to (users_path())
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if(@user.update_attributes(user_params))
      redirect_to (user_path(@user))
    else
      render :edit
    end
  end
  def destroy
    @user = User.find(params[:id])
    name = @user.name
    @user.destroy
    flash[:notice] = "Product #{name} is deleted"
    redirect_to users_path
  end


  def user_params
    params.require(:user).permit(:name, :surname, :username, :email, :password)
  end
  private :user_params
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<h1>Edit event</h1>
<div>
  <%= form_for(@event) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br /><br />
      <%= f.label :description %>
      <%= f.text_area :description %>
      <br/><br/>
      <%= f.label :image %>
      <%= f.text_field :image %>
      <br /><br />
      <%= f.label :date %>
      <%= f.text_field :date %>
      <br />
      <%= f.submit 'Save' %>
  <% end %>
</div>

app/views/events/index.html.erb
<h1>Events</h1>
<ul>
<% @events.each do |event| %>
    <li><%= event.name %>, <%= event.date %>,
      <%= link_to 'Edit', edit_event_path(event) %>,
      <%= link_to 'Read more', event_path(event) %>,
    </li>
<% end %>
</ul>
<p>Add new event</p> <%= link_to 'Add event', new_event_path %>

app/views/events/new.html.erb
<h1>Add event</h1>
<div>
  <%= form_for(@event) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br /><br />
      <%= f.label :description %>
      <%= f.text_area :description %>
      <br/><br/>
      <%= f.label :image %>
      <%= f.text_field :image %>
      <br /><br />
      <%= f.label :date %>
      <%= f.text_field :date %>
      <br />
      <%= f.submit 'Save' %>
  <% end %>
</div>

app/views/events/show.html.erb
<h1>This is product <%= @event.name %></h1>
<% unless flash[:notice].nil? %>
    <div><%= flash[:notice] %></div>
<% end %>

<h3>Product information</h3>
<p><%= @event.image %></p>
<p><%= @event.description %></p>
<p>Date: <%= @event.date %></p>
<p><%= link_to 'Delete event', event_path(@event),method: :delete %></p>

app/views/home/index.html.erb
<h1>This is homepage</h1>

<h2>Add new user</h2>
<%= link_to "Register", new_user_path %>
<%= link_to 'Events', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Community</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<headr>
  <% if current_user %>
      <ul>
        <li><%= current_user.email %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      </ul>
  <% else %>
      <ul>
        <li><%= link_to "Login", 'login' %></li>
      </ul>
  <% end %>
</headr>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Edit user <%= @user.name %></h1>
<div>
  <%= form_for :user, url: '/users' do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br />
      <%= f.label :surname %>
      <%= f.text_field :surname %>
      <br />
      <%= f.label :username %>
      <%= f.text_field :username %>
      <br />
      <%= f.label :email %>
      <%= f.text_field :email %>
      <br/>
      <%= f.label :password %>
      <%= f.password_field  :password %>
      <br/>
      <%= f.submit 'Edit profile' %>
  <% end %>
</div>

app/views/users/index.html.erb
<style>
  .flash{
    color: red;
  }
 </style>
<h1>This is user page, and this is list of users:</h1>
<% unless flash[:notice].nil? %>
    <div class="flash"><%= flash[:notice] %></div>
<% end %>
<div>
  <% @users.each do |user| %>
    <p>Name: <%= user.name %>, <%= user.surname %>, <%= user.email %>, <%= user.id %>, pass: <%= user.password_digest %></p>
      <%= link_to 'Edit', (edit_user_path(user))%>
      <%= link_to 'User details', (user_path(user))%>
      <%= link_to 'Delete User', (user_path(user)), method: :delete %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>This is page for new User</h1>
<div>
  <%= form_for :user, url: '/users' do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br />
      <%= f.label :surname %>
      <%= f.text_field :surname %>
      <br />
      <%= f.label :username %>
      <%= f.text_field :username %>
      <br />
      <%= f.label :email %>
      <%= f.text_field :email %>
      <br/>
      <%= f.label :password %>
      <%= f.password_field  :password %>
      <br/>
      <%= f.submit 'Create profile' %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>This is product page</h1>
<p>
  <%= @user.name %>,
  <%= @user.surname %>,
  <%= @user.email %>,
  <%= @user.username %>
</p>